# Generated by Django 3.0.4 on 2020-03-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
