# Generated by Django 3.0.4 on 2020-03-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayket', '0002_division_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='division',
            new_name='division_id',
        ),
        migrations.AddField(
            model_name='district',
            name='lat',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='lon',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
