# Generated by Django 3.0.4 on 2020-03-13 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayket', '0003_auto_20200313_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='division_id',
            new_name='division',
        ),
    ]
